spring:
  mail:
    host: smtp.gmail.com
    username: sudarshanrbhat.srb@gmail.com
    password: '***'
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false



